// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_xuspc1.h"

/////////////////////////////////////////////////////////////////////////////
// C_Xuspc1

IMPLEMENT_DYNCREATE(C_Xuspc1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// C_Xuspc1 properties

/////////////////////////////////////////////////////////////////////////////
// C_Xuspc1 operations

long C_Xuspc1::GetTimeOutServer()
{
	long result;
	InvokeHelper(0x4003001d, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetTimeOutServer(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x4003001d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

VARIANT C_Xuspc1::GetAscanNumber()
{
	VARIANT result;
	InvokeHelper(0x6803001a, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetAscanNumber(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x6803001a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

VARIANT C_Xuspc1::GetRows()
{
	VARIANT result;
	InvokeHelper(0x68030019, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetRows(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x68030019, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

VARIANT C_Xuspc1::GetCols()
{
	VARIANT result;
	InvokeHelper(0x68030018, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetCols(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x68030018, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

long C_Xuspc1::GetBorderStyle()
{
	long result;
	InvokeHelper(0x68030017, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetBorderStyle(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030017, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

unsigned long C_Xuspc1::GetBackColor()
{
	unsigned long result;
	InvokeHelper(0x68030016, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetBackColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030016, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

long C_Xuspc1::GetBackStyle()
{
	long result;
	InvokeHelper(0x68030015, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetBackStyle(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030015, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

BOOL C_Xuspc1::GetAscanFrameVisible()
{
	BOOL result;
	InvokeHelper(0x68030014, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetAscanFrameVisible(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x68030014, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

long C_Xuspc1::GetAscanFrameStyle()
{
	long result;
	InvokeHelper(0x68030013, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetAscanFrameStyle(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030013, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

unsigned long C_Xuspc1::GetAscanFrameColor()
{
	unsigned long result;
	InvokeHelper(0x68030012, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetAscanFrameColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030012, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

BOOL C_Xuspc1::GetAscanAutoSize()
{
	BOOL result;
	InvokeHelper(0x68030011, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetAscanAutoSize(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x68030011, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

unsigned long C_Xuspc1::GetAscanBackColor()
{
	unsigned long result;
	InvokeHelper(0x68030010, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetAscanBackColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030010, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

BOOL C_Xuspc1::GetAscanGridVisible()
{
	BOOL result;
	InvokeHelper(0x6803000f, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetAscanGridVisible(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x6803000f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

unsigned long C_Xuspc1::GetAscanGridColor()
{
	unsigned long result;
	InvokeHelper(0x6803000e, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetAscanGridColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803000e, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long C_Xuspc1::GetAscanTicksLabelsColor()
{
	unsigned long result;
	InvokeHelper(0x6803000d, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetAscanTicksLabelsColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803000d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

BOOL C_Xuspc1::GetAscanCaptionVisible()
{
	BOOL result;
	InvokeHelper(0x6803000c, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetAscanCaptionVisible(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x6803000c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

unsigned long C_Xuspc1::GetAscanCaptionColor()
{
	unsigned long result;
	InvokeHelper(0x6803000b, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetAscanCaptionColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803000b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long C_Xuspc1::GetAscanColor()
{
	unsigned long result;
	InvokeHelper(0x6803000a, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetAscanColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803000a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long C_Xuspc1::GetGateIFColor()
{
	unsigned long result;
	InvokeHelper(0x68030009, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetGateIFColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030009, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long C_Xuspc1::GetGate1Color()
{
	unsigned long result;
	InvokeHelper(0x68030008, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetGate1Color(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030008, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long C_Xuspc1::GetGate2Color()
{
	unsigned long result;
	InvokeHelper(0x68030007, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetGate2Color(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030007, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

BOOL C_Xuspc1::GetDACVisible()
{
	BOOL result;
	InvokeHelper(0x68030006, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetDACVisible(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x68030006, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL C_Xuspc1::GetRejectVisible()
{
	BOOL result;
	InvokeHelper(0x68030005, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetRejectVisible(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x68030005, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

long C_Xuspc1::GetUnit()
{
	long result;
	InvokeHelper(0x68030004, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetUnit(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030004, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

BOOL C_Xuspc1::GetDACCursorsVisible()
{
	BOOL result;
	InvokeHelper(0x68030003, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetDACCursorsVisible(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x68030003, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

short C_Xuspc1::AscanPositionSize(short iAscan, short Top, short Left, short Width, short Height)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x60030022, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		iAscan, Top, Left, Width, Height);
	return result;
}

short C_Xuspc1::AscanSource(short iAscan, short Board, short Channel, LPCTSTR Server)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_BSTR;
	InvokeHelper(0x60030023, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		iAscan, Board, Channel, Server);
	return result;
}

short C_Xuspc1::AscanCaption(short iAscan, LPCTSTR Caption)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_BSTR;
	InvokeHelper(0x60030024, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		iAscan, Caption);
	return result;
}

void C_Xuspc1::GetDACPoint(double* Position, double* Amplitude)
{
	static BYTE parms[] =
		VTS_PR8 VTS_PR8;
	InvokeHelper(0x60030025, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Position, Amplitude);
}

void C_Xuspc1::GetDACLevel(double* Level)
{
	static BYTE parms[] =
		VTS_PR8;
	InvokeHelper(0x60030026, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Level);
}

BOOL C_Xuspc1::GetAutoRedraw()
{
	BOOL result;
	InvokeHelper(0x68030002, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_Xuspc1::SetAutoRedraw(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x68030002, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

void C_Xuspc1::USPC_Display()
{
	InvokeHelper(0x60030028, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long C_Xuspc1::USPC_Open(LPCTSTR Server, long OpenType)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x60030029, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Server, OpenType);
	return result;
}

long C_Xuspc1::USPC_Close(LPCTSTR Server)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6003002a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Server);
	return result;
}

long C_Xuspc1::USPC_Load(LPCTSTR Server, long Board, long Channel, LPCTSTR file)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x6003002b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Server, Board, Channel, file);
	return result;
}

long C_Xuspc1::USPC_Save(LPCTSTR Server, long Board, long Channel, LPCTSTR file)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x6003002c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Server, Board, Channel, file);
	return result;
}

long C_Xuspc1::USPC_Read(LPCTSTR Server, long Board, long Channel, long unit, LPCTSTR strParam, double* dblValue, VARIANT* dblT1, VARIANT* dblT2, VARIANT* strValue)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_I4 VTS_BSTR VTS_PR8 VTS_PVARIANT VTS_PVARIANT VTS_PVARIANT;
	InvokeHelper(0x6003002d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Server, Board, Channel, unit, strParam, dblValue, dblT1, dblT2, strValue);
	return result;
}

long C_Xuspc1::USPC_Write(LPCTSTR Server, long Board, long Channel, long unit, LPCTSTR strParam, double* dblValue, VARIANT* dblT1, VARIANT* dblT2, VARIANT* strValue, long* clip)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_I4 VTS_BSTR VTS_PR8 VTS_PVARIANT VTS_PVARIANT VTS_PVARIANT VTS_PI4;
	InvokeHelper(0x6003002e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Server, Board, Channel, unit, strParam, dblValue, dblT1, dblT2, strValue, clip);
	return result;
}

short C_Xuspc1::GetVersionMajor()
{
	short result;
	InvokeHelper(0x68030001, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

short C_Xuspc1::GetVersionMinor()
{
	short result;
	InvokeHelper(0x68030000, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}
