#if !defined(AFX__XUSPC1_H__94AA340E_237C_41FA_9203_2FBCB85773FF__INCLUDED_)
#define AFX__XUSPC1_H__94AA340E_237C_41FA_9203_2FBCB85773FF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_Xuspc1 wrapper class

class C_Xuspc1 : public CWnd
{
protected:
	DECLARE_DYNCREATE(C_Xuspc1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xa52f4f97, 0xcb79, 0x443c, { 0xa4, 0x16, 0x42, 0x89, 0xab, 0x6, 0x90, 0xab } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetTimeOutServer();
	void SetTimeOutServer(long nNewValue);
	VARIANT GetAscanNumber();
	void SetAscanNumber(const VARIANT& newValue);
	VARIANT GetRows();
	void SetRows(const VARIANT& newValue);
	VARIANT GetCols();
	void SetCols(const VARIANT& newValue);
	long GetBorderStyle();
	void SetBorderStyle(long nNewValue);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long newValue);
	long GetBackStyle();
	void SetBackStyle(long nNewValue);
	BOOL GetAscanFrameVisible();
	void SetAscanFrameVisible(BOOL bNewValue);
	long GetAscanFrameStyle();
	void SetAscanFrameStyle(long nNewValue);
	unsigned long GetAscanFrameColor();
	void SetAscanFrameColor(unsigned long newValue);
	BOOL GetAscanAutoSize();
	void SetAscanAutoSize(BOOL bNewValue);
	unsigned long GetAscanBackColor();
	void SetAscanBackColor(unsigned long newValue);
	BOOL GetAscanGridVisible();
	void SetAscanGridVisible(BOOL bNewValue);
	unsigned long GetAscanGridColor();
	void SetAscanGridColor(unsigned long newValue);
	unsigned long GetAscanTicksLabelsColor();
	void SetAscanTicksLabelsColor(unsigned long newValue);
	BOOL GetAscanCaptionVisible();
	void SetAscanCaptionVisible(BOOL bNewValue);
	unsigned long GetAscanCaptionColor();
	void SetAscanCaptionColor(unsigned long newValue);
	unsigned long GetAscanColor();
	void SetAscanColor(unsigned long newValue);
	unsigned long GetGateIFColor();
	void SetGateIFColor(unsigned long newValue);
	unsigned long GetGate1Color();
	void SetGate1Color(unsigned long newValue);
	unsigned long GetGate2Color();
	void SetGate2Color(unsigned long newValue);
	BOOL GetDACVisible();
	void SetDACVisible(BOOL bNewValue);
	BOOL GetRejectVisible();
	void SetRejectVisible(BOOL bNewValue);
	long GetUnit();
	void SetUnit(long nNewValue);
	BOOL GetDACCursorsVisible();
	void SetDACCursorsVisible(BOOL bNewValue);
	short AscanPositionSize(short iAscan, short Top, short Left, short Width, short Height);
	short AscanSource(short iAscan, short Board, short Channel, LPCTSTR Server);
	short AscanCaption(short iAscan, LPCTSTR Caption);
	void GetDACPoint(double* Position, double* Amplitude);
	void GetDACLevel(double* Level);
	BOOL GetAutoRedraw();
	void SetAutoRedraw(BOOL bNewValue);
	void USPC_Display();
	long USPC_Open(LPCTSTR Server, long OpenType);
	long USPC_Close(LPCTSTR Server);
	long USPC_Load(LPCTSTR Server, long Board, long Channel, LPCTSTR file);
	long USPC_Save(LPCTSTR Server, long Board, long Channel, LPCTSTR file);
	long USPC_Read(LPCTSTR Server, long Board, long Channel, long unit, LPCTSTR strParam, double* dblValue, VARIANT* dblT1, VARIANT* dblT2, VARIANT* strValue);
	long USPC_Write(LPCTSTR Server, long Board, long Channel, long unit, LPCTSTR strParam, double* dblValue, VARIANT* dblT1, VARIANT* dblT2, VARIANT* strValue, long* clip);
	short GetVersionMajor();
	short GetVersionMinor();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__XUSPC1_H__94AA340E_237C_41FA_9203_2FBCB85773FF__INCLUDED_)
